- include_tasks: install.yml
- include_tasks: install_ansible_requirements.yml
  when: role == "server"
- meta: flush_handlers
- include_tasks: token.yml
  when: role == "server"
- include_tasks: service.yml
