- name: Install environment file
  template:
    src: traefikee-proxy.j2
    dest: /etc/default/traefikee-proxy
    owner: root
    group: root
    mode: '0644'
  notify: Restart traefikee

- name: Install systemd unit file
  template:
    src: traefikee-proxy.service.j2
    dest: /etc/systemd/system/traefikee-proxy.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart traefikee
