version: "3.3"

services:
  traefik:
    image: "traefik:v2.6"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-app:
    image: traefik/whoami:v1.7.1
    command:
      # It tells whoami to start listening on 8082 instead of 80
      - --port=8082
    labels:
      - "traefik.http.routers.my-app.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.services.my-app.loadbalancer.server.port=8082"

# Dashboard (https://localhost:8080)
# Route (http://whoami.docker.localhost/)
# Server port
